version: '3.8'

networks:
  homelab:
    external: true

services:
  # === MONITORING SERVICES ===
  
  # Prometheus Metrics Collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - homelab
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ${CONFIG_ROOT}/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.prometheus.rule=Host("prometheus.${DOMAIN}")'
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=cloudflare"

  # Grafana Monitoring Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASS}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ${CONFIG_ROOT}/grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
    ports:
      - "3002:3000"
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.grafana.rule=Host("grafana.${DOMAIN}")'
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=cloudflare"

  # Uptime Kuma Service Monitoring
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - uptime-kuma_data:/app/data
    ports:
      - "3001:3001"
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.uptime.rule=Host("status.${DOMAIN}")'
      - "traefik.http.routers.uptime.tls=true"
      - "traefik.http.routers.uptime.tls.certresolver=cloudflare"

  # Watchtower Auto Updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://${TELEGRAM_BOT_TOKEN}@telegram?channels=${TELEGRAM_CHAT_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  prometheus_data:
  grafana_data:
  uptime-kuma_data:
