version: '3.8'

networks:
  homelab:
    external: true
  vpn:
    external: true

services:
  # === VPN SERVICES ===
  
  # Gluetun VPN Client
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - vpn
    ports:
      # qBittorrent
      - "8080:8080"
      # Prowlarr
      - "9696:9696"
      # VPN Health Check
      - "8888:8888"
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USER}
      - OPENVPN_PASSWORD=${NORDVPN_PASS}
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - HEALTH_VPN_DURATION_INITIAL=30s
      - HEALTH_TARGET_ADDRESS=1.1.1.1:443
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/gluetun:/gluetun
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AdGuard Home DNS Server
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    networks:
      homelab:
        ipv4_address: 172.20.0.15
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/tcp"
      - "68:68/udp"
      - "3000:3000/tcp"
    volumes:
      - ${CONFIG_ROOT}/adguard/work:/opt/adguardhome/work
      - ${CONFIG_ROOT}/adguard/conf:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(\`dns.${DOMAIN}\`)"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.routers.adguard.tls.certresolver=cloudflare"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"

  # WireGuard VPN Server
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - homelab
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVERURL=${DOMAIN}
      - SERVERPORT=51820
      - PEERS=5
      - PEERDNS=172.20.0.15
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ${CONFIG_ROOT}/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
